In [22]:
import pandas as pd
import lotus
from lotus.models import LM

df_players = pd.read_csv("../../datasets/player_evidence_mine.csv").head(5)[['Player Name']]
df_teams = pd.read_csv("../../datasets/team_evidence.csv")[['Team Name']]

lm = LM(model="ollama/llama3.3:70b")
lotus.settings.configure(lm=lm)

In [23]:
instruction = "The player {Player Name:left} was playing in team {Team Name:right} in 2015."
df = df_players.sem_join(df_teams, instruction)

Join comparisons: 100%|██████████ 150/150 LM Calls [01:47<00:00,  1.39it/s]

In [25]:
df

   Player Name  Team Name
0  Mike Miller       Heat
0  Mike Miller  Grizzlies
0  Mike Miller    Nuggets
0  Mike Miller       Jazz
0  Mike Miller  Cavaliers
1   Quincy Acy   Pelicans
1   Quincy Acy      Kings
1   Quincy Acy     Pacers
1   Quincy Acy      Bulls
1   Quincy Acy       Nets
1   Quincy Acy    Thunder
1   Quincy Acy     Knicks
2  Joe Johnson       Heat
2  Joe Johnson    Rockets
2  Joe Johnson       Nets
2  Joe Johnson      Hawks
2  Joe Johnson     Knicks
3  Brook Lopez       Nets